version: '3.8'

services:
  db_test:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: mnotww_test
    ports:
      - "5432:5432"
    volumes:
      - ./wwmnot.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d mnotww_test"]
      interval: 5s
      timeout: 5s
      retries: 5
